version: '3.8'
services:
  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/cert:/etc/nginx/certs
    networks:
      - ajala_net

  db:
    container_name: ajala_postgres
    image: postgres
    environment:
      POSTGRES_USER: ajala
      POSTGRES_PASSWORD: Ajala42@
      PGDATA: /data/postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - ajala_net
    restart: unless-stopped

  api:
    build:
      context: ./backend/.
    ports:
      - "8000:8000"
    container_name: api
    restart: always
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - db
    networks:
      - ajala_net

  client:
    container_name: client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - ajala_net

volumes:
  db:
    driver: local

networks:
  ajala_net:
    driver: bridge
