
name: push to cbn azure registry
on: 
 push:
    branches:
      - master

env:
  IMAGE_NAME: ${{secrets.CR_IMG_NAME}}

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.AZURE_CR}}
          username: ${{secrets.CR_USERNAME}}
          password: ${{secrets.CR_PASSWORD}}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ${{secrets.AZURE_CR}}/${{secrets.CR_IMG_NAME}}:${{github.sha}}
